class HeavySwagError(Exception): ...


class UnprocessableHeadersFormatError(HeavySwagError): ...


class UnprocessableCookieFormatError(HeavySwagError): ...


class UnsupportedHTTPMethodError(HeavySwagError): ...
